// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetCount provides a mock function with given fields: delta
func (_m *Service) GetCount(delta int) int {
	ret := _m.Called(delta)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(delta)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
